# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispenser.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64ispenser.proto\"\xb2\x02\n\nModbusData\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x0f\n\x07unit_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x1f\n\x05\x63oils\x18\x04 \x03(\x0b\x32\x10.ModbusData.Coil\x12\x36\n\x11holding_registers\x18\x05 \x03(\x0b\x32\x1b.ModbusData.HoldingRegister\x1a&\n\x04\x43oil\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x08\x1al\n\x0fHoldingRegister\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x05\x12\x13\n\tint_value\x18\x02 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x03 \x01(\x02H\x00\x12\x13\n\traw_value\x18\x04 \x01(\x0cH\x00\x42\x07\n\x05valueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispenser_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODBUSDATA._serialized_start=20
  _MODBUSDATA._serialized_end=326
  _MODBUSDATA_COIL._serialized_start=178
  _MODBUSDATA_COIL._serialized_end=216
  _MODBUSDATA_HOLDINGREGISTER._serialized_start=218
  _MODBUSDATA_HOLDINGREGISTER._serialized_end=326
# @@protoc_insertion_point(module_scope)
