# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x1a\x0cnanopb.proto\"`\n\rReadDirectory\x12\x19\n\tdirectory\x18\x01 \x01(\tB\x06\x92?\x03\x08\x80\x02\x12\x19\n\nfile_names\x18\x02 \x03(\tB\x05\x92?\x02\x08 \x12\x19\n\tdir_names\x18\x03 \x03(\tB\x06\x92?\x03\x08\x80\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READDIRECTORY.fields_by_name['directory']._options = None
  _READDIRECTORY.fields_by_name['directory']._serialized_options = b'\222?\003\010\200\002'
  _READDIRECTORY.fields_by_name['file_names']._options = None
  _READDIRECTORY.fields_by_name['file_names']._serialized_options = b'\222?\002\010 '
  _READDIRECTORY.fields_by_name['dir_names']._options = None
  _READDIRECTORY.fields_by_name['dir_names']._serialized_options = b'\222?\003\010\200\002'
  _READDIRECTORY._serialized_start=28
  _READDIRECTORY._serialized_end=124
# @@protoc_insertion_point(module_scope)
