# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ipc_control.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11ipc_control.proto\"\xe7\x01\n\x10IPCControlRegion\x12\x31\n\x14\x64\x61ta_handshake_state\x18\x01 \x01(\x0e\x32\x13.DataHandshakeState\x12/\n\x13\x61pp_handshake_state\x18\x02 \x01(\x0e\x32\x12.AppHandshakeState\x12\x1a\n\x08\x61pp_mode\x18\x03 \x01(\x0e\x32\x08.AppMode\x12\x16\n\x0e\x61pp_buff_depth\x18\x04 \x01(\x05\x12\x16\n\x0e\x61pp_num_frames\x18\x05 \x01(\x05\x12#\n\rapp_log_level\x18\x06 \x01(\x0e\x32\x0c.AppLogLevel*Q\n\x07\x41ppMode\x12\x18\n\x14\x41PP_MODE_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41PP_MODE_CONV_APP\x10\x01\x12\x15\n\x11\x41PP_MODE_TEST_APP\x10\x02*v\n\x0b\x41ppLogLevel\x12\x12\n\x0eLOG_LEVEL_NONE\x10\x00\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x01\x12\x15\n\x11LOG_LEVEL_WARNING\x10\x02\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x03\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x04*O\n\x12\x44\x61taHandshakeState\x12\x13\n\x0f\x44\x41TA_STATE_IDLE\x10\x00\x12$\n DATA_STATE_READY_FOR_CONSUMPTION\x10\x01*F\n\x11\x41ppHandshakeState\x12\x12\n\x0e\x41PP_STATE_IDLE\x10\x00\x12\x1d\n\x19\x41PP_STATE_COMMAND_PENDING\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_control_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPMODE._serialized_start=255
  _APPMODE._serialized_end=336
  _APPLOGLEVEL._serialized_start=338
  _APPLOGLEVEL._serialized_end=456
  _DATAHANDSHAKESTATE._serialized_start=458
  _DATAHANDSHAKESTATE._serialized_end=537
  _APPHANDSHAKESTATE._serialized_start=539
  _APPHANDSHAKESTATE._serialized_end=609
  _IPCCONTROLREGION._serialized_start=22
  _IPCCONTROLREGION._serialized_end=253
# @@protoc_insertion_point(module_scope)
