# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2
import control_inputs_pb2 as control__inputs__pb2
import register_pb2 as register__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmemory.proto\x1a\x0cnanopb.proto\x1a\x14\x63ontrol_inputs.proto\x1a\x0eregister.proto\"\x95\x02\n\rMemoryRequest\x12#\n\toperation\x18\x01 \x01(\x0e\x32\x10.MemoryOperation\x12\x15\n\x06signal\x18\x02 \x01(\tB\x05\x92?\x02\x08@\x12\x15\n\x0bint32_value\x18\x03 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x04 \x01(\x02H\x00\x12\x16\n\x0cuint32_value\x18\x05 \x01(\rH\x00\x12\x1d\n\x0cstring_value\x18\x06 \x01(\tB\x05\x92?\x02\x08@H\x00\x12(\n\x0e\x63ontrol_inputs\x18\x07 \x01(\x0b\x32\x0e.ControlInputsH\x00\x12\x30\n\x12register_interface\x18\x08 \x01(\x0b\x32\x12.RegisterInterfaceH\x00\x42\x07\n\x05value\"\xa7\x02\n\x0eMemoryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12#\n\toperation\x18\x02 \x01(\x0e\x32\x10.MemoryOperation\x12\x15\n\x06signal\x18\x03 \x01(\tB\x05\x92?\x02\x08@\x12\x15\n\x0bint32_value\x18\x04 \x01(\x05H\x00\x12\x15\n\x0b\x66loat_value\x18\x05 \x01(\x02H\x00\x12\x16\n\x0cuint32_value\x18\x06 \x01(\rH\x00\x12\x1d\n\x0cstring_value\x18\x07 \x01(\tB\x05\x92?\x02\x08@H\x00\x12(\n\x0e\x63ontrol_inputs\x18\x08 \x01(\x0b\x32\x0e.ControlInputsH\x00\x12\x30\n\x12register_interface\x18\t \x01(\x0b\x32\x12.RegisterInterfaceH\x00\x42\x07\n\x05value*7\n\x0fMemoryOperation\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x08\n\x04READ\x10\x01\x12\t\n\x05WRITE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MEMORYREQUEST.fields_by_name['signal']._options = None
  _MEMORYREQUEST.fields_by_name['signal']._serialized_options = b'\222?\002\010@'
  _MEMORYREQUEST.fields_by_name['string_value']._options = None
  _MEMORYREQUEST.fields_by_name['string_value']._serialized_options = b'\222?\002\010@'
  _MEMORYRESPONSE.fields_by_name['signal']._options = None
  _MEMORYRESPONSE.fields_by_name['signal']._serialized_options = b'\222?\002\010@'
  _MEMORYRESPONSE.fields_by_name['string_value']._options = None
  _MEMORYRESPONSE.fields_by_name['string_value']._serialized_options = b'\222?\002\010@'
  _MEMORYOPERATION._serialized_start=646
  _MEMORYOPERATION._serialized_end=701
  _MEMORYREQUEST._serialized_start=69
  _MEMORYREQUEST._serialized_end=346
  _MEMORYRESPONSE._serialized_start=349
  _MEMORYRESPONSE._serialized_end=644
# @@protoc_insertion_point(module_scope)
